### ISSUE TITLE
Accessibility Insights from inventory

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#108]

**Comment by danielhonker** [comment]
I'll check in with @sarahscottr on this to see how we want to integrate it into briefings with SDL, BRMs, and CTO this week.

**Comment by danielhonker** [comment]
[Insights slide deck](https://docs.google.com/presentation/d/1-YorG5eTR9IpCEiBlh1eEB6lc2wbcxqUXDBtXwqHnos/edit?usp=sharing)

**Comment by danielhonker** [comment]
@sarahscottr Good stuff in here. Seems like the majority of services (and departments) don't have guidance on how to make their services more accessible right now (in all facets of access). What other takeaways did you have in doing the analysis? What insights would you share with the resource teams in other depts?

**Comment by sammodabber** [comment]
@sarahscottr Pull out info for HRD and CPIO

**Comment by sammodabber** [comment]
On hold due to remote work  - Sarah to update CPIO on Service Access
