### ISSUE TITLE
Plan for how we will route departments/services to SDL

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#117]
How we will prioritize services for SDL services
SDL schedule for forms workshops and projects
How we will handoff and communicate to departments

**Comment by sammodabber** [comment]
SDL has requested that we refer departments to office hours. Various workshops do not have an official schedule kept somewhere

**Comment by danielhonker** [comment]
Closing this after our meeting on the topic. [Notes are here.](https://docs.google.com/document/d/1nm73T28s5o5BA1gCBF1K_eH-mv4x6Eu-74lCcTG7btw/edit)
