### ISSUE TITLE
v1 framework for prioritization

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#13]
- [x] draft a framework
- [x] schedule a work session to develop it into a rubric we could use

**Comment by danielhonker** [comment]
Make sure the building blocks of prioritization are correct
Crosswalk prioritization framework to the data sources we have/can get -- what does each data source tell us for prioritization?

**Comment by ADoAboutThings** [comment]
Hey I got some rough crib notes from the Canadian Digital Service 
[2018-10-30 Service prioritisation from CDS.pdf](https://github.com/cityofaustin/serviceaccess/files/3252851/2018-10-30.Service.prioritisation.from.CDS.pdf)

**Comment by danielhonker** [comment]
Here's v1 prioritization framework we fleshed out this week: 

**Services that are “high priority” for redesign/digitization are services that**:
- Impact a large number of residents
- Are critical to the people they serve
- Residents come into contact with a lot
- Affect SD23 priorities
- Promote racial equity
- Enable operational efficiencies (ex: time or cost savings, shared tools and services)
- Generate revenues or funding
- Help preparedness or risk mitigation (ex: disaster preparedness)

**Each of these maps to a bucket:**
- Breadth of community impact
- Depth of community impact
- Benefit to city government operations

**Factors that define each of these:**
https://airtable.com/tblqUpz9CiyxuX4U1/viwQkYdaOgC98jFS6?blocks=hide 

**Next steps**:
- [x] Draft this iteration into some content we could publish
- [x] Stress test the framework with real services to define the indicators

**Comment by danielhonker** [comment]
Done for v1 = A breakdown of factors and indicators for each factor that we could use to assess priority. v1 should be divergent, and we do not need to address weighting of different factors at this point.
