### ISSUE TITLE
Set up project documentation site

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#17]
Similar to what we've done in the past with http://projects.austintexas.io/ 

- [x] @danielhonker set up platform -- Gitbook
- [ ] @sarahscottr draft content & architecture

**Comment by danielhonker** [comment]
Shell is set up here https://app.gitbook.com/@cityofaustin/s/service-access-project/

**Comment by sarahscottr** [comment]
Connected with Jeff in content. He's agreed to lend capacity to do copy writing and review.
