### ISSUE TITLE
Add accessibility content to documentation site

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#23]
Now that we have a high-level framework for accessibility, we need to turn it into content we can publish to the documentation site.

**Comment by ADoAboutThings** [comment]
Draft copy for our gitbooks documentation site: 

[What does accessibility mean for Service Access? ](https://docs.google.com/document/d/1EVvT821EkgREXxy5hazM42owRubBZAPmhJLwua-WFL8/edit#)

**Comment by danielhonker** [comment]
Combining content on accessibility and prioritization into an "Our approach" page: https://docs.google.com/document/d/1LnqjZp7tUfogBy6ADDltx1b-dZYL8YSVO1D2jK26WIc/edit#heading=h.jm4ao0wavzmf
