### ISSUE TITLE
Plan for how content audit will connect with inventory

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#24]
Determine how service access and the atx.gov content audits will work together. 

A few opportunity areas:
- Form creation -- both the PDF scrape and content audit can feed a backlog of forms to digitize
- Content audits can flag access issues. What information could the content audit be capturing/tagging?
- Compare insights from content audit with our service questionnaire (i.e., how does the service manager’s description of the service compare with what is online?)

Next steps -- talk again with Laura the week of July 22
- Attend sprint review on July 25 -- they will be reviewing content audit work so far
- Touch base on how we want the content audit and service access to work together
  - What information to collect/tag in the audit that is helpful to service access
  - How do we want to share findings
  - How might content audit prioritize departments, with service access prioritization framework
- Share the questionnaire with the content audit team. Some potential connections here too. 

[Notes](https://docs.google.com/document/d/1wlysya0br5CAqMBZINrmLAj_ej6f6bcxZkRZVZKm4gY/edit?usp=sharing) from @danielhonker 's convo with @LauraTrujillo

**Comment by danielhonker** [comment]
Content audits in progress: 311, CPIO, Animal Center, Purchasing
Mark, Anu, and Matthew = content audit specialists

Meeting on Thurs 7/18 to see how the templates are working. @manlinyao to join and advise on any additional information to collect. Ex:

- What services have multiple entry points -- phone, online, in person
- Collection of personally identifiable information -- could cause users to bounce 

By end of next week (7/26), establish a good workflow for audits in each sprint. 

#14  is being organized by department too.

**Comment by danielhonker** [comment]
Do we want to give the content audit team some priorities of departments or services to assess?
Give them the PDF scrape.

**Comment by LauraTrujillo** [comment]
@danielhonker Yes, please!!!

**Comment by ADoAboutThings** [comment]
Synced up with the content audit team on Thursday, August 1st to run through service access framework. 

Here is a link to ongoing content audits segmented by departments here: [Content Audits](https://drive.google.com/drive/folders/19l_uFP3vIh7na1uwm9N8HXzySosGI6HP)

**Comment by danielhonker** [comment]
@manlinyao  to check in on when content team will deliver complete audit.
