### ISSUE TITLE
Co-creation plan for accessibility and prioritization frameworks

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#3]
How to engage:

- Champions in other departments
- Other stakeholders in other departments
- Advocates who help us get to the end user

**Comment by danielhonker** [comment]
Map out the network and the players -- know who the advocates are

**Comment by danielhonker** [comment]
@sarahscottr working on a first pass of a network list -- expected by early week of July 22

**Comment by danielhonker** [comment]
Schedule a workshop and start designing -- week of July 22. Equity Office can help us promote it to Equity Action Team.

**Comment by ADoAboutThings** [comment]
[-Co-Creation Planning Document ](https://docs.google.com/document/d/1l4z4MBPDFkXfdnMAnn9oNR7dpMBDkntR6-TQ7uUBTk8/edit#heading=h.lu3njgcze75b)
