### ISSUE TITLE
Medium post: Approach to accessibility (Aug 2019)

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#42]
How we are defining accessibility for an inventory of City services

**Comment by benguhin** [comment]
I'm imagining pulling most of this from the CTTC presentation in February (and we can include the video from ATXN at the bottom of the article): https://docs.google.com/presentation/d/1PjVoO5-J7z97lkU6Y_UU8Z7uAKQuUxo-vmDEP7lZoOU/edit?usp=sharing
