### ISSUE TITLE
Co-creation workshop for accessibility framework

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#49]
Planning slides: https://docs.google.com/presentation/d/1HPPi53umDRwoNWzZHURdLpG9KyMa2_fy3rbzfJ-hLuw/edit?usp=sharing

https://docs.google.com/document/d/1l4z4MBPDFkXfdnMAnn9oNR7dpMBDkntR6-TQ7uUBTk8/edit#heading=h.lu3njgcze75b

**Comment by sarahscottr** [comment]
@sarahscottr 
- Contacted Houmma for translation services (need to follow up)
- Scheduled time to design workshop with Manlin and Andrew
- Got information about catering (need to follow up with catering options to get quotes)
- Booked Cepeda Library (in the process fo booking Chestnut in case the are more attendees than estimated)

To do: 
- Look at considerations for translating presentation materials and designing an accessible workshop

@danielhonker will follow up on Sign Language interpreter

**Comment by danielhonker** [comment]
Got the request form back from Lee Nguyen in HR. Will need to look at this in the design of the session.

**Comment by danielhonker** [comment]
Scheduled for 9/12. Reserved Cepeda library. 
@sarahscottr @manlinyao @ADoAboutThings to meet and design the workshop. 

Outreach:

- @sarahscottr will also reach out to TX School for the Blind. 
- @sarahscottr working on invitation language to share with the orgs we have identified. Then get the eventbrite up. 
- Target to send out the invitation by Aug 16

**Comment by danielhonker** [comment]
Eventbrite online: https://bit.ly/austinaccess 

Reaching out to service providers for outreach. Also sharing with Equity Office.

Trying to get a quote from caterer that does dietary restrictions well. 

Emailed Lee about live captioning. ASL translation is confirmed. @sarahscottr is arranging for Spanish translation through CPIO. 

Need to get bus passes

Will meet as a team next week to review workshop plans.

**Comment by danielhonker** [comment]
William will share photos and we'll put them here.
