### ISSUE TITLE
Decide questionnaire tool & workflow

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#58]
Sub-issues to decide:

1) What is the workflow we are asking respondents to follow. Ex 1: Fill out a form for your service, one at a time. Ex 2: Populate rows in a spreadsheet, where you can fill in information for multiple services at the same time. Need to consider:

  - How many services is a respondent going to complete the questionnaire for? Ex: Is one respondent going to fill it out for 5 services (spreadsheet workflow may be better) or for one service (form is better).
  - What information do we want to pre-populate on their services?
  - Who has the required information for each service? Does only one person have the information for each service, or is it spread across multiple people?

2) Tool requirements coming from the questionnaire design (#22): 

  - Need for conditional/skip logic
  - What types of data we need to collect (i.e., text, images, video, URLs, etc.)
  - What type of analysis we want to do on the data we get
  - Need for relational data tables

**Comment by ADoAboutThings** [comment]
These are the design specs for the content of the actual questionnaire itself:

[Design goals for the service access questionnaire](https://docs.google.com/document/d/1fMZKHjkr7RtgwKa8DWimBCAcZ3sb827rckIAlx2KLJM/edit#heading=h.iovtu4tn7g7s) 

This is where we are mocking up the questions: 

[Accessibility Framework Questionnaire](https://docs.google.com/spreadsheets/d/1i_Wd-7C7XRThK4zSd9JbGWCrYi7daJWlRq72iRKpYek/edit#gid=158529156)

Looking to mock this up on airtable (though it is likely not the right tool for the job): 

[Service Access Questionnaire mock-up on airtable ](https://airtable.com/invite/l?inviteId=invt3RLXBlFDbOoqu&inviteToken=e77cc0a9a634c25c2ae6859382eba856b7a801b3ca017c85620ec2c1e4be1739)

**Comment by easherma** [comment]
@desigonz maybe this would be a good thing to test out Formstack with?

**Comment by danielhonker** [comment]
Tracking potential tools and eval criteria here: https://docs.google.com/spreadsheets/d/1uRcaTeXb9IoSm3ERyU8x5_dhSgTQnCKzP69ikWYTrDc/edit#gid=701589117

**Comment by danielhonker** [comment]
Workflow decisions:

- Provide both a form and spreadsheet to input information
- When we do outreach to departments, provide them with the full list of services that we've already identified for them. And ask them to submit information for their top 10 services among those. 
- Will probably architect this with different tools for the form input, spreadsheet input, and database for analysis

Tasks
- [x] Decision on form tool
- [x] Decision on spreadsheet tool
- [x] Decision on database tool
- [ ] Set up all of our tools
- [ ] Set up our master service list with all the data that has
- [ ] Draft the outreach email template
- [ ] Organize the services we've identified for each department

![Image from iOS (1)](https://user-images.githubusercontent.com/17604266/64822453-a3106d80-d57a-11e9-895a-c5a673615523.jpg)
