### ISSUE TITLE
Create accessibility definition + framework

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#6]
- [x] draft a framework with all the aspects that comprise access
- [x] Invite Chase, Tori, content team, Taylor for feedback -- in groups
- [x] Plan for stakeholder process to workshop the framework (incl meeting with iTeam)

Links to frameworks here to borrow from here: https://airtable.com/tblrnRRKH2o74h1RK/viwpawesLKoKBvKMA?blocks=hide

**Comment by danielhonker** [comment]
- [x] Check in on research week of June 3 -- google hangout work session

**Comment by ADoAboutThings** [comment]
Today meeting with CDS to get some insight into their "paperless" prioritization framework. 

Reachng out to Calvin Goings who is the director listed responsible for Seattle's "affordable" service inventory

**Comment by ADoAboutThings** [comment]
**Here are a few notes**

-[Ongoing Accessibility research](https://docs.google.com/document/d/16APTmBZX-QleTTv2DZa43mbtggDvhdRv_M_O31ZIkhE/edit#)
-[Accessibility Assessment Questionnaire  ](https://docs.google.com/document/d/1y-jMgfjYMRWdkuGKLzy0bOqUj2NVZRI-1Sn0b_tzyhw/edit#)

**Comment by danielhonker** [comment]
Looking to close out v1 of the accessibility framework before 6/27 workshop. I'll schedule a work session for when @ADoAboutThings is back in ATX.

**Comment by ADoAboutThings** [comment]
>     * [ ]  Check in on research week of June 3 -- google hangout work session

These are the follow-up notes I have from Slack:

Andrew Do [6:16 PM]
Thanks for the call y’all and miss you all. Here are the action items I took away so let me know if there’s anything missing.

*Action Items*

-Follow-up with @Nameir M on separate process mapping convo
-Follow-up with @Manlin Yao and @sarahsr on remaining research gaps to fill
on baseline stuff
-Flush out the “buckets” of assessment and re-orient it to better match the journey of accessing a service from a prospective beneficiary point-of-view
-Add other elements like feedback access, physical access, etc.

**Comment by ADoAboutThings** [comment]
Digitized brainstorm:


[Digitized Brainstorm on Airtable](https://airtable.com/tblK1Yz2q36Thq5JM/viw80VweTZYlH8Nhk?blocks=hide)

**Comment by danielhonker** [comment]
Let's call v1 of this framework done. We'll be meeting with web and content teams today to flesh out the next more detailed iteration.
