### ISSUE TITLE
Synthesis wrapup

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#86]
Goals:

- Converge on key themes from our engagements
- Articulate those themes so that we can close feedback loop and document what we've learned
- Identify how we want to share out/document those themes

Next steps:
- [x] Tag everything and write up insights. Get help with wordsmithing
- [x] Decide artifacts to create to share out insights: Medium post, presentations to close loops, visualizations
- [x] Find some content help on those artifacts ^^
- [ ] Determine what resources are available for these insights. Connect with #73 

Want to know from the insights:
- What do the insights tell us about our access framework? Where do they confirm the framework? Where do they identify something new or more nuanced? Need to tag the insights by stage in our access framework.
- Tag the insights by the venue or medium: in person, online, etc. Want to show what we learned most relevant to CTM's role in tech.
-  What insights are not addressed in our questionnaire? Not that something is missing -- just that the questionnaire has natural limitations.

**Comment by sarahscottr** [comment]
Hey @srigdon and @annieszot tagging you on this issue, since as part of the share out we're planning to publish an article to Medium.

The link's here - https://docs.google.com/document/d/1bfnHlycEcCJeD1fou4n4dTDk4FwJGWUD1LDxp1-i8eU/edit?usp=sharing

Hoping for first round of edit by EOW next week (the week of 12/2). Let me know if that's too soon.

**Comment by annieszot** [comment]
Sounds great @sarahscottr ! Marked to work on this Wednesday 11/27 :)

**Comment by annieszot** [comment]
Suggested edits added @sarahscottr

**Comment by sarahscottr** [comment]
Thanks @annieszot! Made corrections and additions on edits. Ready for the final round/review.
