### ISSUE TITLE
Identify next steps with resource teams

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#96]
- [x] Talk to each resource team about:
• Here's the inventory. What of this would be valuable to you?
• How might we share or promote the resources you provide, for the services that come out of this inventory?
• What are your resource constraints and concerns?
• Would you be interested in a broader conversation about organizing to give these services more resources, and resources for your programs?

- [ ] Come back together on what we learn from these conversations, ideally before Thanksgiving. Then decide next steps

Outreach list: 
- [x] Redesigning forms (Soolin + Andrew/Chris for forms workshop) @danielhonker 
- [x] Online payments (Controller) @danielhonker 
- [x] SDL @danielhonker 
- [x] ADA program @danielhonker 
- [x] Digital inclusion @danielhonker 
- [x] Content readability (content team) @sarahscottr 
- [x] Language access (Houmma) @sarahscottr 
- [x] Community engagement (CPIO) @sarahscottr 
- [x] Equity @sarahscottr

**Comment by sarahscottr** [comment]
Notes on the CPIO, Equity, and Content conversation -
https://docs.google.com/document/d/1EQaF7IcjfQuCgrXSsq06lA1enYAMceSq112hzOM8jZg/edit?usp=sharing

**Comment by sarahscottr** [comment]
@danielhonker could you share your notes from your meetings? Thanks!
