### ISSUE TITLE
Medium articles - Installation and Frameworks

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/serviceaccess#97]

**Comment by sarahscottr** [comment]
Hey @annieszot attached are the links for the two articles. Thanks again for your help!!!!! Let me know it's two much on top of your schedule with the upcoming holiday stuff and we can discuss other options/how to space them out.

https://docs.google.com/document/d/1qfXl_6KOUf_rxmOjZt4CsO6INKwc-gsiKCrmMHZiKho/edit?usp=sharing

https://docs.google.com/document/d/19CMIetdfmpRcYcZDzdH1UiX9k46A4WPvjxK555Fnedk/edit?usp=sharing

**Comment by annieszot** [comment]
Suggested edits added @sarahscottr ! With the forms installation, just write out "portable document format" before the first set of acronyms :) Well done!

**Comment by danielhonker** [comment]
It's alliiiiiiiiiiiiiiiive!!!!
https://medium.com/civiqueso/re-imaging-the-city-of-austins-website-as-physical-space-143b670f49a5
